<?php

/**
 * @file
 * Contains imp_safety_info.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imp_safety_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.imp_safety_info':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Displays the important safety information about the product.') . '</p>';
      return $output;
  }
}
